spring:
  application:
    name: short
  jpa:
    show-sql: true
  datasource:
    url: jdbc:h2:mem:short
    username:
    password:
    h2:
      console:
        enabled: true
    driver-class-name: org.h2.Driver
  liquibase:
    change-log: db/changelog/db.changelog-master.yaml
    enabled: true